#!/bin/bash

. lib.sh || exit 1

account_name=${1}

if [ -z ${account_name} ]; then
    fail "Usage: $0 <account name>"
fi

set -u

read -e -p "What is the AWS access key : " access_key;
read -e -p "What is the AWS secret key : " secret_key;

cat <<EOF >  "${account_name}-itsre-bootstrap.json"
[
  {
    "account_id": "${account_name}",
    "aws_access_key_id": "${access_key}",
    "aws_secret_access_id": "${secret_key}"
  }
]
EOF

encrypt "${account_name}-itsre-bootstrap.json"
safedelete "${account_name}-itsre-bootstrap.json"

unset access_key
unset secret_key
